/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "fsm.h"
#include "elevator.h"
#include "elevator_io_device.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_fsm_onInitBetweenFloors(void);
extern void test_fsm_onRequestButtonPress(void);
extern void test_fsm_onFloorArrival(void);
extern void test_fsm_onDoorTimeout(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/testFsm.c");
  run_test(test_fsm_onInitBetweenFloors, "test_fsm_onInitBetweenFloors", 19);
  run_test(test_fsm_onRequestButtonPress, "test_fsm_onRequestButtonPress", 28);
  run_test(test_fsm_onFloorArrival, "test_fsm_onFloorArrival", 72);
  run_test(test_fsm_onDoorTimeout, "test_fsm_onDoorTimeout", 108);

  return UnityEnd();
}
